bandPage/bandPage/urls.py
from django.contrib import admin
from django.urls import path, include


# Note I'm leaving path for user_auth and silverbyskyline blank
# as url's will be dealt with in their respective url.py files.
urlpatterns = [
    path('', include('user_auth.urls')),
    path('', include('silverbyskyline.urls')),
    path('admin/', admin.site.urls),
]

bandPage/silverbyskyline/urls.py
from django.urls import path, include, re_path
from django.views.generic import ListView, DetailView
from . import views
from .models import Post

''' This urls.py script pertains to band pages provides a url to each corresponding view outlined in views.py. '''



app_name = 'silverbyskyline'
urlpatterns = [
    path('', views.silverbyskyline, name='silverbyskyline'),
    path('bandupdates/',
        ListView.as_view(
            queryset=
            Post.objects.all().order_by("-date")[:10],
            template_name="updates.html"          
            ),
        name='bandupdates'),
    path('bandupdates/<int:pk>/',
        DetailView.as_view(
            model = Post,
            template_name="post.html"
            )
        ),
]

bandPage/user_auth/urls.py
from django.urls import path, include, re_path
from . import views
from django.contrib import admin
from django.contrib.auth import views as auth_views

''' This urls.py script pertains to user_auth pages provides a url to each corresponding view outlined in views.py. '''

app_name = 'user_auth'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), {'next_page': 'login'}, name='logout'),
    path('register/', views.register, name='register'),
]

bandPage/silverbyskyline/models.py
from django.db import models

from embed_video.fields import EmbedVideoField

# Create your models here.

class Post(models.Model):
    '''
    This class creates the Post model.

    The Post model is utilised to create blog-style update posts.

    :param str title: The title of the post
    
    :param str body: The body of the post
    
    :param DateTime date: The date the post was made

    :returns: The title of the post
    :rtype: str
    
    '''
    # Default behaviour - Django creates primary keys for you
    title = models.CharField(max_length=140)    
    body = models.TextField()
    date = models.DateTimeField()

    def __str__(self):
        return self.title

# Adding the below to try and include video players

class Video(models.Model):
    '''
    This class creates the Video model.

    The Video model is utilised to embed a youtube video on the page.

    :param str title: The title of the video
    
    :param DateTime added: The date when the video was added
    
    :param str url: The url of the video

    :returns: The title of the post
    :rtype: str
    
    '''
    title = models.CharField(max_length=100)
    added = models.DateTimeField(auto_now_add=True, null=True)
    url = EmbedVideoField()

    def __str__(self):
        return str(self.title)

    class Meta:
        ordering = ['-added']

bandPage/user_auth/models.py
from django.db import models

# Create your models here.

bandPage/user_auth/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    '''
    This class creates the SignUpForm.

    The form is used to permit new users to sign up to the website.

    :param str first-name: The users first name
    :param str username: The username selected by the user
    :param str password1: The password selected by the user
    :param str password2: The password selected by the user a second time for verification purposes

    :returns: The title of the post
    :rtype: str
    
    '''
    first_name = forms.CharField(max_length=30, required=True, help_text='Optional.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'password1', 'password2', )

bandPage/silverbyskyline/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .models import Video

# Create your views here.

# Below we use @login_required to redirect the user back to the log
# in / sign up page when they try to view polls when they aren't
# logged in.  I previously had this at the #Vote method but it still
# permitted users to see the voting buttons and click vote, which
# I didn't think was very clear that they weren't actually voting.
@login_required(login_url='/login')
def silverbyskyline(request):
    '''
    This function renders home.html.

    The page is rendered at a url supplied by urls.py and loads the provide youtube video(s).

    :param Video Videos: A list of videos
    
    :returns: home.html rendered
    :rtype: html request
    
    '''
    # The code below grabs the required video before the page loads
    videos = Video.objects.all()
    return render(request, 'index.html', context={'videos': videos})

bandPage/user_auth/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from user_auth.forms import SignUpForm

# Create your views here.

def login_user(request):
    ''' This function renders login.html '''
    return render(request, 'registration/login.html')

# Old placeholder register method superseded below
# def register(request):
#    return HttpResponse("Welcome to the registration page.")

# Followed this tutorial on how to make a register page with custom inputs:
# https://simpleisbetterthancomplex.com/tutorial/2017/02/18/how-to-create-user-sign-up-view.html#sign-up-with-extra-fields
def register(request):
    '''
    This function registers new users.

    If registration is successful it redirects the now logged in user to the home page.
    If not it redirects them back to the registration page.
    
    '''    
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request,user)
            return redirect('silverbyskyline:silverbyskyline')
    else:
        form = SignUpForm()
    return render(request, 'registration/register.html', {'form': form})

bandPage/silverbyskyline/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}L2T23 Task{% endblock %}</title>
  <style>
      p {
        font-family: Arial, Helvetica;
      }

      body {
        background-color: #263238;
      }

  </style>
</head>
<body class = "text-white">
  <header>
    {% if user.is_authenticated %}
      Hi {{ user.username }}!
      <a href="{% url 'user_auth:logout' %}">logout</a>
    {% else %}
      <a href="{% url 'user_auth:login' %}">login</a>
    {% endif %}
  </header>
  <hr>
  <main>
    {% block content %}
    {% endblock %}
  </main>
  <hr>
  <footer>
    </form>
    <!-- Adds a link which takes us to the homepage! -->
      <a href="{% url 'silverbyskyline:silverbyskyline' %}">
        SilverbySkyline
      </a>
    </form>
  </footer>
</body>
</html>

bandPage/silverbyskyline/templates/home.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="main.css">

    <title> Homepage </title>
    <!-- Open a browser and note how this is the name of the tab! -->

    <style>
        p {
          font-family: Arial, Helvetica;
        }

        body {
          background-color: #263238;
        }

    </style>

  </head>
  <body>
    <section class = "text-white">
      {% extends 'base.html' %}
      {% load embed_video_tags %}

      {% block content %}

      <h2>SilverbySkyline</h2>

      {% for item in videos %}

        <!-- The line below should be presenting an embedded video but its not - why? -->
        <!-- Source: https://www.youtube.com/watch?v=dGF1x14QNGA -->
        <!-- It is fetching the url and setting the size correctly but nothing is showing -->
        {% video item.url '640x480' %}
        {{ item.title }}

      {% endfor %}

      <form>
        <!-- Adds a link which takes us to the register url! -->
        <a href="{% url 'silverbyskyline:bandupdates' %}">
          View latest band updates here!
        </a>
      </form>

      {% endblock %}

    </section>
  </body>
</html>

bandPage/silverbyskyline/templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="main.css">

    <title> Homepage </title>
    <!-- Open a browser and note how this is the name of the tab! -->

    <style>
        p {
          font-family: Arial, Helvetica;
        }

        body {
          background-color: #263238;
        }

    </style>

  </head>
  <body>
    <section class = "text-white">
      {% extends 'base.html' %}
      {% load embed_video_tags %}

      {% block content %}

      <h2>SilverbySkyline</h2>

      {% for item in videos %}

        <!-- The line below should be presenting an embedded video but its not - why? -->
        <!-- Source: https://www.youtube.com/watch?v=dGF1x14QNGA -->
        <!-- It is fetching the url and setting the size correctly but nothing is showing -->
        {% video item.url '640x480' %}
        {{ item.title }}

      {% endfor %}

      <form>
        <!-- Adds a link which takes us to the register url! -->
        <a href="{% url 'silverbyskyline:bandupdates' %}">
          View latest band updates here!
        </a>
      </form>

      {% endblock %}

    </section>
  </body>
</html>

bandPage/silverbyskyline/templates/post.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="main.css">

    <title> Homepage </title>
    <!-- Open a browser and note how this is the name of the tab! -->

    <style>
        p {
          font-family: Arial, Helvetica;
        }

        body {
          background-color: #263238;
        }

    </style>

  </head>
  <body>
    <section class = "text-white">

      {% extends 'base.html' %}

      {% block title %}{{ post.title }}{% endblock %}

      {% block content %}
      <h3><a href="/bandupdates/{{post.id}}">{{ post.title }}</a></h3>
      <h6> on {{ post.date }}</h6>
      <div class = "container">
        {{ post.body|safe|linebreaks}}
      </div>
      <form>
        <!-- Adds a link which takes us to the band updates main page! -->
        <a href="{% url 'silverbyskyline:bandupdates' %}">
          Go back!
        </a>
      </form>
      <br><br>
      {% endblock %}
    </section>
  </body>
</html>

bandPage/silverbyskyline/templates/updates.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="main.css">

    <title> Latest Band Updates </title>
    <!-- Open a browser and note how this is the name of the tab! -->

    <style>
        p {
          font-family: Arial, Helvetica;
        }

        body {
          background-color: #263238;
        }

    </style>

  </head>
  <body>
    <section class = "text-white">

      {% extends 'base.html' %}

      {% block title %}Login{% endblock %}

      {% block content %}
        {% for post in object_list %}
        <h5>{{ post.date|date:"Y-m-d" }}<a href="/bandupdates/{{post.id}}">
          {{ post.title }}</a></h5>
        {% endfor %}
      {% endblock %}

    </section>
  </body>
</html>